### ISSUE TITLE
Lab 5.1: Incorrect Solution for Question 2

### ISSUE THREAD

**Issue by Tomiwa-dev** [ClickHouse/clickhouse-academy#10]
Question 2: How many properties were sold for over 1 million pounds in 2022?

Solution Provided: `SELECT count()
FROM uk_price_paid
WHERE price > 1_000_000; `

Year isn't taken into consideration. 
![Screenshot 2024-05-26 at 06 14 15](https://github.com/ClickHouse/clickhouse-academy/assets/78116662/5b3c0114-fb35-4e46-9775-7983df5e522e)

**Comment by pmusa** [comment]
Thank you very much for reporting. This was fixed in #11 and sorry for not seeing your message before (fixed my notification settings).
