### ISSUE TITLE
TTL using now() is not supported

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/clickhouse-academy#4]
Module 11 uses `TTL now() + INTERVAL 1 MONTH`. It's not a trivial fix because it's in the recording, so maybe we add a comment or something to state it's not supported anymore.

![Screenshot 2024-05-01 at 11 45 51](https://github.com/ClickHouse/clickhouse-academy/assets/5323324/6e252ec5-c80a-49c0-8036-62f5a5e4111b)
![Screenshot 2024-05-01 at 11 45 31](https://github.com/ClickHouse/clickhouse-academy/assets/5323324/c3e1c994-1317-4e2f-8c88-841bdc6f3941)

**Comment by pmusa** [comment]
this is fixed.
